apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: exam-yayazhang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nathansegers/big_data_and_ai-24_may_api:versie1
        ports:
        - containerPort: 80